.TH GUESS-UPSTREAM-METADATA 1 'November 2022' 'guess-upstream-metadata 0.1.29' 'User Commands'
.SH NAME
guess-upstream-metadata \- guess upstream package metadata
.SH DESCRIPTION
guess\-upstream\-metadata [\-h] [\-\-trust] [\-\-disable\-net\-access] [\-\-check] [\-\-consult\-external\-directory] [\-\-version] [path]
This tool tries to guess upstream metadata (Homepage, Contact, VCS Repository)
for an upstream project. It does this by parsing various files in the
package, and possibly calling out to external services (unless --disable-net-access is specified).
.SS "positional arguments:"
.IP
path
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-trust\fR
Whether to allow running code from the package.
.TP
\fB\-\-disable\-net\-access\fR
Do not probe external services.
.TP
\fB\-\-check\fR
Check guessed metadata against external sources.
.TP
\fB\-\-consult\-external\-directory\fR
Pull in external (not maintained by upstream)
directory data
.TP
\fB\-\-version\fR
show program's version number and exit
.SH "SEE ALSO"
\&\fIapply-multiarch-hints\fR\|(1)
\&\fIguess-upstream-metadata\fR\|(1)
\&\fIlintian-brush\fR\|(1)
\&\fIlintian\fR\|(1)
.SH AUTHORS
Jelmer Vernooĳ <jelmer@jelmer.uk>
