def drop_vcs_in_scheme(url: str) -> str: ...

def unsplit_vcs_url(repo_url: str, branch: str | None, subpath: str | None) -> str: ...

def probe_gitlab_host(hostname: str) -> bool: ...

def is_gitlab_site(hostname: str, net_access: bool | None = None) -> bool: ...

def guess_repo_from_url(url: str, net_access: bool | None = None) -> str | None: ...

def probe_gitlabb_host(hostname: str) -> bool: ...

def find_public_repo_url(url: str, net_access: bool | None = None) -> str | None: ...

def browse_url_from_repo_url(url: str, branch: str | None = None, subpath: str | None = None, net_access: bool | None = None) -> str | None: ...

def plausible_vcs_url(url: str) -> bool: ...

def plausible_vcs_browse_url(url: str) -> bool: ...

def probe_upstream_branch_url(url: str, version: str | None = None) -> bool | None: ...

def canonical_git_repo_url(url: str, net_access: bool | None = None) -> str: ...

def check_repository_url_canonical(url: str, version: str | None = None) -> str: ...
